
- hosts: windows_web

  tasks:
    - name: add user operator
      win_user:
        name: operator
        password: 0p$4@ll

    - name: Add or update registry path MyCompany, with entry 'hello', and containing 'world'
      win_regedit:
        key: HKCU:\Software\MyCompany
        name: hello
        data: world

    - name: Install Web Server
      win_feature:
        name: Web-Server
        state: present

    - name: Create web directory
      win_file:
        path: c:\www
        state: directory

    - name: Create web index
      win_lineinfile:
        path: C:\www\index.html
        create: yes
        line: "Hello World from {{ ansible_hostname }} at {{ ansible_ssh_host }}"

    - name: Build web site
      win_iis_website:
        name: "Web site"
        hostname: "www.{{ ansible_ssh_host }}.xip.io"
        physical_path: c:\www


