- hosts: lab_server
  become: yes

  tasks:
   - name: Install Apache
     yum:
       name: httpd
       state: present

   - name: Configure Apache
     template:
       src: templates/httpd.conf.j2
       dest: /etc/httpd/conf.d/httpd.conf
     notify: restart httpd


  handlers:
   - name: restart httpd
     service:
       name: httpd
       state: restarted

