- hosts: f5_ltm
  connection: local
  
  vars:
    web_server_ip: 132.200.20.10

  tasks:
    - name: "Add {{ web_server_ip }} to my-pool"
      bigip_pool:
        server: "{{ ansible_ssh_host }}"
        server_port: 8443
        user: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: no

        state: "present"
        name: "my-pool"
        address: "{{ web_server_ip }}"
        port: 80

