- hosts: lab_server
  
  vars:
    ntp_servers:
      - hostname: pool.ntp.org

    SELinux_booleans:
      - { name: 'samba_enable_home_dirs', state: 'on' }
      - { name: 'ssh_sysadm_login', state: 'on', persistent: 'yes' }

  roles:
    - role: rhel-system-roles.timesync
    - role: rhel-system-roles.selinux

