- hosts: lab_server

  tasks:
    - name: Install Maven from archive
      unarchive:
        remote_src: yes
        src: http://apache.mesi.com.ar/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.tar.gz
        dest: /opt/

    - name: Link Maven to /usr/bin
      file:
        src: /opt/apache-maven-3.5.0/bin/mvn
        dest: /usr/bin/mvn
        state: link

    - name: Install Jboss EAP Group
      yum:
       name: "@jboss-eap7"
       state: present

    - name: Start Jboss Service
      service:
        name: eap7-standalone.service
        state: started

    - name: Enable 8080/tcp
      firewalld:
        port: 8080/tcp
        state: enabled

    - name: Wait for Application Availability
      wait_for:
        host: "{{ ansible_ssh_host }}"
        port: 8080
      delegate_to: localhost
  

